// src/app/layout.js
"use client";
import { Inter } from "next/font/google";
import "./globals.css";
import { store, persistor } from "@/store/store";
import Link from "next/link";
import { Provider } from "react-redux";
import { PersistGate } from "redux-persist/integration/react"; // Import PersistGate
import Navbar from "@/components/Navbar";

// const inter = Inter({ subsets: ["latin"] });

// export const metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        <Provider store={store}>
          <PersistGate loading={null} persistor={persistor}>
            {/* <Navbar /> */}
            {children}
          </PersistGate>
        </Provider>
      </body>
    </html>
  );
}
